<a href="https://colab.research.google.com/github/God-Orcale/AI_Test/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [4]:
data =[[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [7]:
x_ones = torch.ones_like(x_data)
print(f"ones tensor: {x_ones}\n")
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(f"Random Tensor:{x_rand}\n")

ones tensor: tensor([[1, 1],
        [1, 1]])

Random Tensor:tensor([[0.4022, 0.2546],
        [0.3536, 0.3220]])



In [8]:
shape =(2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"random tensor:\n {rand_tensor}\n")
print(f"ones tensor\n {ones_tensor}\n")
print(f"zeros tennsor:\n {zeros_tensor}")

random tensor:
 tensor([[0.0996, 0.0471, 0.3047],
        [0.8378, 0.0920, 0.7610]])

ones tensor
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros tennsor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [10]:
if torch.accelerator.is_available():
  tensor = tensor.to(torch.accelerator.current_accelerator())

In [16]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[...,-1]}")
tensor[:,1]=0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [17]:
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [18]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
print(f"y1:\n {y1}")
print(f"y2:\n {y2}")
print(f"y3:\n {y3}")

torch.matmul(tensor,tensor.T,out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
print(f"z1:\n {z1}")
print(f"z2:\n {z2}")
print(f"z3:\n {z3}")
torch.matmul(tensor,tensor.T,out=z3)

y1:
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2:
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3:
 tensor([[0.9189, 0.6052, 0.4595, 0.4546],
        [0.7774, 0.5959, 0.1463, 0.1099],
        [0.5194, 0.2569, 0.5275, 0.5674],
        [0.9575, 0.9913, 0.2616, 0.4187]])
z1:
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z2:
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z3:
 tensor([[0.6851, 0.7697, 0.7881, 0.7186],
        [0.4394, 0.0734, 0.4010, 0.0714],
        [0.0616, 0.0589, 0.4763, 0.7697],
        [0.5547, 0.4600, 0.4072, 0.7629]])


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [19]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item,type(agg_item))

12.0 <class 'float'>


In [20]:
print(f"{tensor}\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [21]:
t =torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [22]:
t.add_(1)
print(f"t:{t}")
print(f"n:{n}")

t:tensor([2., 2., 2., 2., 2.])
n:[2. 2. 2. 2. 2.]


In [23]:
n = np.ones(5)
t = torch.from_numpy(n)

In [24]:
np.add(n,1,out=n)
print(f"t:{t}")
print(f"n:{n}")

t:tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n:[2. 2. 2. 2. 2.]
