<a href="https://colab.research.google.com/github/God-Orcale/AI_Test/blob/main/Tensor_introduce_by_ytb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import math

In [2]:
x = torch.empty(3,4)
print(type(x))
print(x)
# 创建张量的最简单方法是使用调用：torch.empty()

<class 'torch.Tensor'>
tensor([[2.3032e-03, 0.0000e+00, 2.3031e-03, 0.0000e+00],
        [2.3822e-44, 3.0386e+29, 2.9217e-07, 0.0000e+00],
        [2.3032e-03, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [3]:
zero = torch.zeros(2,3)
print(zero)
one = torch.ones(2,3)
print(one)
torch.manual_seed(1729)
random = torch.rand(2,3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [4]:
torch.manual_seed(1729)
random1 = torch.rand(2,3)
print(random1)

random2 = torch.rand(2,3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2,3)
print(random3)

random4 = torch.rand(2,3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [16]:
x = torch.empty(2,3,4)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

# 我们调用empty_like().、zeros_like()、ones_like()和rand_like()方法。
# 使用该属性.shape，我们可以验证这些方法中的每一个都返回一个相同的维度和范围。

torch.Size([2, 3, 4])
tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  2.0319e-43,  0.0000e+00]],

        [[ 2.3122e-03,  0.0000e+00, -2.1571e-10,  4.4128e-41],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 3, 4])
tensor([[[-2.1571e-10,  4.4128e-41, -2.1571e-10,  4.4128e-41],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  2.0319e-43,  0.0000e+00]],

        [[ 2.3122e-03,  0.0000e+00,  2.1571e-10,  4.4128e-41],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 3, 4])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torc

In [17]:
some_constants = torch.tensor([[3.1415926,2.71828],[1.61803,0.0072897]])
print(some_constants)

some_integers = torch.tensor((2,3,5,7,11,13,17,19))
print(some_integers)

more_integers = torch.tensor(((2,4,6),[3,6,9]))
print(more_integers)


tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [18]:
a = torch.ones((2,3),dtype= torch.int16)
print(a)
b = torch.rand((2,3),dtype= torch.float64) *20
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[15.6871, 19.1964,  8.3775],
        [ 3.8887,  0.9265, 10.5135]], dtype=torch.float64)
tensor([[15, 19,  8],
        [ 3,  0, 10]], dtype=torch.int32)


In [19]:
ones = torch.zeros(2,2)+1
twos = torch.ones(2,2)*2
threes = (torch.ones(2,2)*7-1)/2
fours = twos ** 2
sqrt2s = twos **0.5
print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [21]:
powers2 = twos ** torch.tensor([[1,2],[3,4]])
print(powers2)
fives = ones +fours
print(fives)
dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [22]:
rand = torch.rand(2,4)
doubled = rand * (torch.ones(1,4)*2)
print(rand)
print(doubled)
# 广播规则是：
# 每个张量必须至少有一个维度 - 没有空张量。
# 比较两个张量的维度大小，从最后一个到第一个：
# 每个维度必须相等，或者其中一个维度的大小必须为 1，或者维度不存在于其中一个张量中

tensor([[0.2152, 0.0813, 0.7199, 0.2617],
        [0.4047, 0.0177, 0.3361, 0.7429]])
tensor([[0.4304, 0.1627, 1.4398, 0.5233],
        [0.8093, 0.0354, 0.6723, 1.4857]])


In [23]:
a = torch.ones(4,3,2)
b = a*torch.rand( 3,2)
print(b)
c = a*torch.rand( 3,1)
print(c)
d = a * torch.rand(1,2)
print(d)

tensor([[[0.4492, 0.9244],
         [0.2081, 0.4120],
         [0.3000, 0.5434]],

        [[0.4492, 0.9244],
         [0.2081, 0.4120],
         [0.3000, 0.5434]],

        [[0.4492, 0.9244],
         [0.2081, 0.4120],
         [0.3000, 0.5434]],

        [[0.4492, 0.9244],
         [0.2081, 0.4120],
         [0.3000, 0.5434]]])
tensor([[[0.6819, 0.6819],
         [0.8889, 0.8889],
         [0.0919, 0.0919]],

        [[0.6819, 0.6819],
         [0.8889, 0.8889],
         [0.0919, 0.0919]],

        [[0.6819, 0.6819],
         [0.8889, 0.8889],
         [0.0919, 0.0919]],

        [[0.6819, 0.6819],
         [0.8889, 0.8889],
         [0.0919, 0.0919]]])
tensor([[[0.8537, 0.9432],
         [0.8537, 0.9432],
         [0.8537, 0.9432]],

        [[0.8537, 0.9432],
         [0.8537, 0.9432],
         [0.8537, 0.9432]],

        [[0.8537, 0.9432],
         [0.8537, 0.9432],
         [0.8537, 0.9432]],

        [[0.8537, 0.9432],
         [0.8537, 0.9432],
         [0.8537, 0.9432]]])


In [25]:
# 执行数学运算
a = torch.rand(2,4) *2 -1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5,0.5))
angles = torch.tensor([0,math.pi/4,math.pi/2,3*math.pi/4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\n Sine and arcsine:')
print(angles)
print(sines)
print(inverses)

print('\n Bitwise XOR:')
b = torch.tensor([1,5,11])
c = torch.tensor([2,7,10])
print(torch.bitwise_xor(b,c))

print('\n Broadcasted ,element-wise equality comparison:')
d = torch.tensor([[1,2.],[3.,4.]])
e = torch.ones(1,2)
print(torch.eq(d,e))

print('\n Reduction ops:')
print(torch.max(d))
print(torch.max(d).item())
print(torch.mean(d))
print(torch.std(d))
print(torch.prod(d))
print(torch.unique(torch.tensor([1,2,1,2,1,2])))
v1 = torch.tensor([1.,0.,0.])
v2 = torch.tensor([0.,1.,0.])
m1 = torch.rand(2,2)
m2 = torch.tensor([[3.,0.],[0.,3.]])

print('\n Vectors & Matrices')
print(torch.linalg.cross(v2,v1))
print(m1)
m3 = torch.linalg.inv(m1)
print(m3)
print(torch.linalg.svd(m3))

Common functions:
tensor([[0.6321, 0.7917, 0.7417, 0.3902],
        [0.6292, 0.5922, 0.7634, 0.7433]])
tensor([[-0., 1., 1., -0.],
        [1., -0., 1., 1.]])
tensor([[-1.,  0.,  0., -1.],
        [ 0., -1.,  0.,  0.]])
tensor([[-0.5000,  0.5000,  0.5000, -0.3902],
        [ 0.5000, -0.5000,  0.5000,  0.5000]])

 Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

 Bitwise XOR:
tensor([3, 2, 1])

 Broadcasted ,element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

 Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

 Vectors & Matrices
tensor([ 0.,  0., -1.])
tensor([[0.2459, 0.3499],
        [0.2853, 0.9091]])
tensor([[ 7.3492, -2.8290],
        [-2.3066,  1.9879]])
torch.return_types.linalg_svd(
U=tensor([[-0.9380,  0.3467],
        [ 0.3467,  0.9380]]),
S=tensor([8.3879, 0.9638]),
Vh=tensor([[-0.9172,  0.3985],
        [ 0.3985,  

In [27]:
# 从torch.sin()中可以看到，调用张量是a.add_(b)中更改的张量地方。
a = torch.tensor([0,math.pi/4,math.pi/2,3*math.pi/4])
print('a:')
print(a)
print(torch.sin(a))
print(a)

b = torch.tensor([0,math.pi/4,math.pi/2, 3*math.pi/4])
print('\n b:')
print(b)
print(torch.sin_(b))
print(b)

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

 b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [28]:
a = torch.ones(2,2)
b = torch.rand(2,2)
print('Before:')
print(a)
print(b)
print('n \After adding:')
print(a.add_(b))
print(a)
print(b)
print('\n After multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.5695, 0.7206],
        [0.4155, 0.0982]])
n \After adding:
tensor([[1.5695, 1.7206],
        [1.4155, 1.0982]])
tensor([[1.5695, 1.7206],
        [1.4155, 1.0982]])
tensor([[0.5695, 0.7206],
        [0.4155, 0.0982]])

 After multiplying
tensor([[0.3243, 0.5193],
        [0.1727, 0.0096]])
tensor([[0.3243, 0.5193],
        [0.1727, 0.0096]])


In [29]:
a = torch.rand(2,2)
b = torch.rand(2,2)
c = torch.zeros(2,2)
old_id = id(c)
print(c)
d = torch.matmul(a,b,out=c)
print(c)

assert c is d
assert id(c)==old_id

torch.rand(2,2,out=c)
print(c)
assert id(c) == old_id

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.3903, 0.0101],
        [0.3287, 0.0123]])
tensor([[0.2775, 0.0935],
        [0.1874, 0.3136]])


In [30]:
a = torch.ones(2,2)
b = a
a[0][1] = 561
print(b)

tensor([[  1., 561.],
        [  1.,   1.]])


In [31]:
a = torch.ones(2,2)
b =a.clone()

assert b is not a
print(torch.eq(a,b))
a[0][1]=561
print(b)

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [32]:
a = torch.rand(2,2,requires_grad=True)
print(a)
b = a.clone()
print(b)
c = a.detach().clone()
print(c)

print(a)

tensor([[0.7793, 0.8340],
        [0.3402, 0.9330]], requires_grad=True)
tensor([[0.7793, 0.8340],
        [0.3402, 0.9330]], grad_fn=<CloneBackward0>)
tensor([[0.7793, 0.8340],
        [0.3402, 0.9330]])
tensor([[0.7793, 0.8340],
        [0.3402, 0.9330]], requires_grad=True)


In [33]:
if torch.accelerator.is_available():
  print("We have an accelerator!")
else:
  print('Sorry,CPU only.')

Sorry,CPU only.


In [35]:
# 有多种方法可以将数据传输到目标设备上。你 可以在创建时执行此作
my_device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else torch.device('cpu')  # 将torch.device('cpu')放在同一行
print('Device:{}'.format(my_device))

x = torch.rand(2,2,device=my_device)
print(x)


Device:cpu
tensor([[0.5609, 0.9791],
        [0.3976, 0.5647]])


In [39]:
import torch

# 检查 CUDA 是否可用，若不可用则使用 CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# 在选定的设备上创建张量
x = torch.rand(2, 2, device=device)
y = torch.rand(2, 2, device=device)
z = x + y  # 现在 x 和 y 在同一个设备上，不会报错

print(z)

Using device: cpu
tensor([[0.1724, 0.4018],
        [0.9612, 0.9296]])


In [6]:
a = torch.rand(3,226,226)
b = a.unsqueeze(0)
print(a.shape)
print(b.shape)


torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [7]:
c = torch.rand(1,1,1,1,1)
print(c)

tensor([[[[[0.1895]]]]])


In [8]:
a = torch.rand(1,20)
print(a.shape)
print(a)
b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2,2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.9562, 0.8896, 0.7035, 0.9211, 0.1784, 0.2168, 0.4146, 0.2654, 0.0098,
         0.2950, 0.6072, 0.3663, 0.4035, 0.4121, 0.0695, 0.5390, 0.1751, 0.4792,
         0.1661, 0.5460]])
torch.Size([20])
tensor([0.9562, 0.8896, 0.7035, 0.9211, 0.1784, 0.2168, 0.4146, 0.2654, 0.0098,
        0.2950, 0.6072, 0.3663, 0.4035, 0.4121, 0.0695, 0.5390, 0.1751, 0.4792,
        0.1661, 0.5460])
torch.Size([2, 2])
torch.Size([2, 2])


In [9]:
a = torch.ones(4,3,2)
c = a*torch.rand( 3,1)
print(c)

tensor([[[0.4265, 0.4265],
         [0.5256, 0.5256],
         [0.9091, 0.9091]],

        [[0.4265, 0.4265],
         [0.5256, 0.5256],
         [0.9091, 0.9091]],

        [[0.4265, 0.4265],
         [0.5256, 0.5256],
         [0.9091, 0.9091]],

        [[0.4265, 0.4265],
         [0.5256, 0.5256],
         [0.9091, 0.9091]]])


In [10]:
a = torch.ones(4,3,2)
b = torch.rand( 3)
c = b.unsqueeze(1)
print(c.shape)
print(a*c)

torch.Size([3, 1])
tensor([[[0.2780, 0.2780],
         [0.2162, 0.2162],
         [0.9831, 0.9831]],

        [[0.2780, 0.2780],
         [0.2162, 0.2162],
         [0.9831, 0.9831]],

        [[0.2780, 0.2780],
         [0.2162, 0.2162],
         [0.9831, 0.9831]],

        [[0.2780, 0.2780],
         [0.2162, 0.2162],
         [0.9831, 0.9831]]])


In [11]:
# squeeze() unsqueeze() squeeze_() unsqueeze_()
batch_me = torch.rand(3,226,226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [12]:
output3d = torch.rand(6,20,20)
print(output3d.shape)
input1d = output3d.reshape(6*20*20)
print(input1d.shape)

print(torch.reshape(output3d,(6*20*20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


In [13]:
import numpy as np
numpy_array = np.ones((2,3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [14]:
pytorch_rand = torch.rand(2,3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.3713, 0.5356, 0.8788],
        [0.2939, 0.6085, 0.8147]])
[[0.37127358 0.5355865  0.87883186]
 [0.29386652 0.60853326 0.81471366]]


In [15]:
numpy_array[1,1] = 23
print(pytorch_tensor)
pytorch_rand[1,1] =17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.37127358  0.5355865   0.87883186]
 [ 0.29386652 17.          0.81471366]]
